// format: slug -> display name

export const REALM_DATA = {
  us: {
    atiesh: "Atiesh",
    myzrael: "Myzrael",
    "old-blanchy": "Old Blanchy",
    azuresong: "Azuresong",
    mankrik: "Mankrik",
    pagle: "Pagle",
    ashkandi: "Ashkandi",
    westfall: "Westfall",
    whitemane: "Whitemane",
    faerlina: "Faerlina",
    grobbulus: "Grobbulus",
    "bloodsail-buccaneers": "Bloodsail Buccaneers",
    remulos: "Remulos",
    arugal: "Arugal",
    yojamba: "Yojamba",
    skyfury: "Skyfury",
    sulfuras: "Sulfuras",
    windseeker: "Windseeker",
    benediction: "Benediction",
    earthfury: "Earthfury",
    maladath: "Maladath",
    angerforge: "Angerforge",
    eranikus: "Eranikus",
  },
  eu: {
    everlook: "Everlook",
    auberdine: "Auberdine",
    lakeshire: "Lakeshire",
    chromie: "Chromie",
    "pyrewood-village": "Pyrewood Village",
    "mirage-raceway": "Mirage Raceway",
    razorfen: "Razorfen",
    "nethergarde-keep": "Nethergarde Keep",
    sulfuron: "Sulfuron",
    golemagg: "Golemagg",
    patchwerk: "Patchwerk",
    firemaw: "Firemaw",
    flamegor: "Flamegor",
    gehennas: "Gehennas",
    venoxis: "Venoxis",
    "hydraxian-waterlords": "Hydraxian Waterlords",
    mograine: "Mograine",
    amnennar: "Amnennar",
    ashbringer: "Ashbringer",
    transcendence: "Transcendence",
    earthshaker: "Earthshaker",
    giantstalker: "Giantstalker",
    mandokir: "Mandokir",
    thekal: "Thekal",
    jindo: "Jin'do",
  },
  kr: {
    "shimmering-flats": "Shimmering Flats",
    lokholar: "Lokholar",
    iceblood: "Iceblood",
    ragnaros: "Ragnaros",
    frostmourne: "Frostmourne",
  },
} as const;

export type Region = keyof typeof REALM_DATA;
export type RealmSlug<T extends Region> = keyof (typeof REALM_DATA)[T];
